# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import status_pb2 as status__pb2


class TasksStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/status.Tasks/GetStatus',
                request_serializer=status__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=status__pb2.GetStatusResponse.FromString,
                )
        self.GetStatusById = channel.unary_unary(
                '/status.Tasks/GetStatusById',
                request_serializer=status__pb2.GetStatusByIdRequest.SerializeToString,
                response_deserializer=status__pb2.GetStatusByIdResponse.FromString,
                )
        self.GetStatusByName = channel.unary_unary(
                '/status.Tasks/GetStatusByName',
                request_serializer=status__pb2.GetStatusByNameRequest.SerializeToString,
                response_deserializer=status__pb2.GetStatusByNameResponse.FromString,
                )
        self.CreatStatus = channel.unary_unary(
                '/status.Tasks/CreatStatus',
                request_serializer=status__pb2.CreateStatusRequest.SerializeToString,
                response_deserializer=status__pb2.CreateStatusResponse.FromString,
                )
        self.UpdatStatus = channel.unary_unary(
                '/status.Tasks/UpdatStatus',
                request_serializer=status__pb2.UpdateStatusRequest.SerializeToString,
                response_deserializer=status__pb2.UpdateStatusResponse.FromString,
                )
        self.DeletStatus = channel.unary_unary(
                '/status.Tasks/DeletStatus',
                request_serializer=status__pb2.DeleteStatusRequest.SerializeToString,
                response_deserializer=status__pb2.DeleteStatusResponse.FromString,
                )


class TasksServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatusById(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatusByName(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreatStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TasksServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=status__pb2.GetStatusRequest.FromString,
                    response_serializer=status__pb2.GetStatusResponse.SerializeToString,
            ),
            'GetStatusById': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatusById,
                    request_deserializer=status__pb2.GetStatusByIdRequest.FromString,
                    response_serializer=status__pb2.GetStatusByIdResponse.SerializeToString,
            ),
            'GetStatusByName': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatusByName,
                    request_deserializer=status__pb2.GetStatusByNameRequest.FromString,
                    response_serializer=status__pb2.GetStatusByNameResponse.SerializeToString,
            ),
            'CreatStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatStatus,
                    request_deserializer=status__pb2.CreateStatusRequest.FromString,
                    response_serializer=status__pb2.CreateStatusResponse.SerializeToString,
            ),
            'UpdatStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatStatus,
                    request_deserializer=status__pb2.UpdateStatusRequest.FromString,
                    response_serializer=status__pb2.UpdateStatusResponse.SerializeToString,
            ),
            'DeletStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletStatus,
                    request_deserializer=status__pb2.DeleteStatusRequest.FromString,
                    response_serializer=status__pb2.DeleteStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'status.Tasks', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Tasks(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/status.Tasks/GetStatus',
            status__pb2.GetStatusRequest.SerializeToString,
            status__pb2.GetStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatusById(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/status.Tasks/GetStatusById',
            status__pb2.GetStatusByIdRequest.SerializeToString,
            status__pb2.GetStatusByIdResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatusByName(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/status.Tasks/GetStatusByName',
            status__pb2.GetStatusByNameRequest.SerializeToString,
            status__pb2.GetStatusByNameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CreatStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/status.Tasks/CreatStatus',
            status__pb2.CreateStatusRequest.SerializeToString,
            status__pb2.CreateStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdatStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/status.Tasks/UpdatStatus',
            status__pb2.UpdateStatusRequest.SerializeToString,
            status__pb2.UpdateStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeletStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/status.Tasks/DeletStatus',
            status__pb2.DeleteStatusRequest.SerializeToString,
            status__pb2.DeleteStatusResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
