# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: status.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cstatus.proto\x12\x06status\"4\n\nTaskStatus\x12\x11\n\tstatus_id\x18\x01 \x01(\x05\x12\x13\n\x0bstatus_name\x18\x02 \x01(\t\"\x12\n\x10GetStatusRequest\"7\n\x11GetStatusResponse\x12\"\n\x06status\x18\x01 \x03(\x0b\x32\x12.status.TaskStatus\")\n\x14GetStatusByIdRequest\x12\x11\n\tstatus_id\x18\x01 \x01(\x05\";\n\x15GetStatusByIdResponse\x12\"\n\x06status\x18\x01 \x01(\x0b\x32\x12.status.TaskStatus\"-\n\x16GetStatusByNameRequest\x12\x13\n\x0bstatus_name\x18\x01 \x01(\t\"=\n\x17GetStatusByNameResponse\x12\"\n\x06status\x18\x01 \x01(\x0b\x32\x12.status.TaskStatus\"9\n\x13\x43reateStatusRequest\x12\"\n\x06status\x18\x01 \x01(\x0b\x32\x12.status.TaskStatus\")\n\x14\x43reateStatusResponse\x12\x11\n\tstatus_id\x18\x01 \x01(\x05\"9\n\x13UpdateStatusRequest\x12\"\n\x06status\x18\x01 \x01(\x0b\x32\x12.status.TaskStatus\"\x16\n\x14UpdateStatusResponse\"(\n\x13\x44\x65leteStatusRequest\x12\x11\n\tstatus_id\x18\x01 \x01(\x05\"\x16\n\x14\x44\x65leteStatusResponse2\xc9\x03\n\x05Tasks\x12@\n\tGetStatus\x12\x18.status.GetStatusRequest\x1a\x19.status.GetStatusResponse\x12L\n\rGetStatusById\x12\x1c.status.GetStatusByIdRequest\x1a\x1d.status.GetStatusByIdResponse\x12R\n\x0fGetStatusByName\x12\x1e.status.GetStatusByNameRequest\x1a\x1f.status.GetStatusByNameResponse\x12H\n\x0b\x43reatStatus\x12\x1b.status.CreateStatusRequest\x1a\x1c.status.CreateStatusResponse\x12H\n\x0bUpdatStatus\x12\x1b.status.UpdateStatusRequest\x1a\x1c.status.UpdateStatusResponse\x12H\n\x0b\x44\x65letStatus\x12\x1b.status.DeleteStatusRequest\x1a\x1c.status.DeleteStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'status_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASKSTATUS']._serialized_start=24
  _globals['_TASKSTATUS']._serialized_end=76
  _globals['_GETSTATUSREQUEST']._serialized_start=78
  _globals['_GETSTATUSREQUEST']._serialized_end=96
  _globals['_GETSTATUSRESPONSE']._serialized_start=98
  _globals['_GETSTATUSRESPONSE']._serialized_end=153
  _globals['_GETSTATUSBYIDREQUEST']._serialized_start=155
  _globals['_GETSTATUSBYIDREQUEST']._serialized_end=196
  _globals['_GETSTATUSBYIDRESPONSE']._serialized_start=198
  _globals['_GETSTATUSBYIDRESPONSE']._serialized_end=257
  _globals['_GETSTATUSBYNAMEREQUEST']._serialized_start=259
  _globals['_GETSTATUSBYNAMEREQUEST']._serialized_end=304
  _globals['_GETSTATUSBYNAMERESPONSE']._serialized_start=306
  _globals['_GETSTATUSBYNAMERESPONSE']._serialized_end=367
  _globals['_CREATESTATUSREQUEST']._serialized_start=369
  _globals['_CREATESTATUSREQUEST']._serialized_end=426
  _globals['_CREATESTATUSRESPONSE']._serialized_start=428
  _globals['_CREATESTATUSRESPONSE']._serialized_end=469
  _globals['_UPDATESTATUSREQUEST']._serialized_start=471
  _globals['_UPDATESTATUSREQUEST']._serialized_end=528
  _globals['_UPDATESTATUSRESPONSE']._serialized_start=530
  _globals['_UPDATESTATUSRESPONSE']._serialized_end=552
  _globals['_DELETESTATUSREQUEST']._serialized_start=554
  _globals['_DELETESTATUSREQUEST']._serialized_end=594
  _globals['_DELETESTATUSRESPONSE']._serialized_start=596
  _globals['_DELETESTATUSRESPONSE']._serialized_end=618
  _globals['_TASKS']._serialized_start=621
  _globals['_TASKS']._serialized_end=1078
# @@protoc_insertion_point(module_scope)
