# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tasks.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btasks.proto\x12\x05tasks\"I\n\x04Task\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61te\x18\x04 \x01(\t\"\x11\n\x0fGetTasksRequest\".\n\x10GetTasksResponse\x12\x1a\n\x05tasks\x18\x01 \x03(\x0b\x32\x0b.tasks.Task\"%\n\x12GetTaskByIdRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\"0\n\x13GetTaskByIdResponse\x12\x19\n\x04task\x18\x01 \x01(\x0b\x32\x0b.tasks.Task\".\n\x11\x43reateTaskRequest\x12\x19\n\x04task\x18\x01 \x01(\x0b\x32\x0b.tasks.Task\"%\n\x12\x43reateTaskResponse\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\".\n\x11UpdateTaskRequest\x12\x19\n\x04task\x18\x01 \x01(\x0b\x32\x0b.tasks.Task\"\x14\n\x12UpdateTaskResponse\"$\n\x11\x44\x65leteTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\"\x14\n\x12\x44\x65leteTaskResponse2\xd3\x02\n\x05Tasks\x12;\n\x08GetTasks\x12\x16.tasks.GetTasksRequest\x1a\x17.tasks.GetTasksResponse\x12\x44\n\x0bGetTaskById\x12\x19.tasks.GetTaskByIdRequest\x1a\x1a.tasks.GetTaskByIdResponse\x12\x41\n\nCreateTask\x12\x18.tasks.CreateTaskRequest\x1a\x19.tasks.CreateTaskResponse\x12\x41\n\nUpdateTask\x12\x18.tasks.UpdateTaskRequest\x1a\x19.tasks.UpdateTaskResponse\x12\x41\n\nDeleteTask\x12\x18.tasks.DeleteTaskRequest\x1a\x19.tasks.DeleteTaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tasks_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TASK']._serialized_start=22
  _globals['_TASK']._serialized_end=95
  _globals['_GETTASKSREQUEST']._serialized_start=97
  _globals['_GETTASKSREQUEST']._serialized_end=114
  _globals['_GETTASKSRESPONSE']._serialized_start=116
  _globals['_GETTASKSRESPONSE']._serialized_end=162
  _globals['_GETTASKBYIDREQUEST']._serialized_start=164
  _globals['_GETTASKBYIDREQUEST']._serialized_end=201
  _globals['_GETTASKBYIDRESPONSE']._serialized_start=203
  _globals['_GETTASKBYIDRESPONSE']._serialized_end=251
  _globals['_CREATETASKREQUEST']._serialized_start=253
  _globals['_CREATETASKREQUEST']._serialized_end=299
  _globals['_CREATETASKRESPONSE']._serialized_start=301
  _globals['_CREATETASKRESPONSE']._serialized_end=338
  _globals['_UPDATETASKREQUEST']._serialized_start=340
  _globals['_UPDATETASKREQUEST']._serialized_end=386
  _globals['_UPDATETASKRESPONSE']._serialized_start=388
  _globals['_UPDATETASKRESPONSE']._serialized_end=408
  _globals['_DELETETASKREQUEST']._serialized_start=410
  _globals['_DELETETASKREQUEST']._serialized_end=446
  _globals['_DELETETASKRESPONSE']._serialized_start=448
  _globals['_DELETETASKRESPONSE']._serialized_end=468
  _globals['_TASKS']._serialized_start=471
  _globals['_TASKS']._serialized_end=810
# @@protoc_insertion_point(module_scope)
